### ISSUE TITLE
INFO com.oath.halodb.Uns  - OHC using JNA OS native malloc/free Out of memory!!!

### ISSUE THREAD

**Issue by ShuaiJunlan** [yahoo/HaloDB#10]
I got a logging info `INFO com.oath.halodb.Uns  - OHC using JNA OS native malloc/free Out of memory!!!`
Why does that information come up? How can I change the `Java Memory` configuration ?

**Comment by amannaly** [comment]
Could you please provide some more details; how much memory is available on the box you are running HaloDB, how many keys are you storing and what are the size of keys. Also have you enabled the [memory pool](https://github.com/yahoo/HaloDB/blob/master/src/main/java/com/oath/halodb/HaloDBOptions.java#L144) ?

HaloDB stores all the keys in an index in memory for fast lookups, therefore we need to make sure that there is enough memory for all the keys.

**Comment by archenroot** [comment]
@shuaijunlan - how many keys and what is the structure of average key you use?

Thank you for answer.

**Comment by wangtao724** [comment]
Closing because no more details provided
