### ISSUE TITLE
update to enable usage on windows

### ISSUE THREAD

**Issue by rfecher** [yahoo/HaloDB#13]
Any comment on PR #12?

Here's the background:
based on the other comments in this file, it is known that this won't work in windows, and results in fatal exceptions https://grokbase.com/t/lucene/dev/1519kz2s50/recent-java-9-commit-e5b66323ae45-breaks-fsync-on-directory

It seems appropriate to allow for the situation where a file channel cannot be created on a directory because in that situation (Windows) fsync is not applicable either.

**Comment by amannaly** [comment]
Thank you for the PR and sorry for the delay. I have added some comments to the PR. Could you please take a look.

**Comment by wangtao724** [comment]
Close as the PR https://github.com/yahoo/HaloDB/pull/12 has been merged.
