### ISSUE TITLE
What I can store in HalloDB?

### ISSUE THREAD

**Issue by archenroot** [yahoo/HaloDB#16]
Imagine my both key and value might be:
simple data types to complex object structures (coming from JSON, YAML files)

Value also could be for example avro schema, json schema, json, messagepack message, whatever.

Is this supported?

Also now imagine key is json:
{
     group: ingestion
     type: schema
     key: datasource1Pipeline
}

{
     group: ingestion
     type: schema
     key: datasource2Pipeline
}

and value is real schema content for both. Now imagine I am going to search for all keys from group ingestion by providing: 
{
     group: ingestion
} I expect all keys with group will be returned.

Is HalloDB designed to implement such query capabilities easily? (I didn't dig down more into the source code yet...)

Now I am going to search by key:

**Comment by archenroot** [comment]
@ahasani - thx for answer. yeah that was also my idea to make the key simply composite as pure string. Ok, in case of VALUE, am I limited somehow or I can really store anything?

**Comment by ahasani** [comment]
Hi @archenroot, HaloDB uses byte[] as its key and value, so yes you can store anything anything that can be turned to byte[] which is virtually anything including serializable objects with size less than or equal to Integer.MAX_VALUE

Cheers
