### ISSUE TITLE
Max key length is hardcoded to `Byte.MAX_VALUE` (127)

### ISSUE THREAD

**Issue by akhodakivskiy** [yahoo/HaloDB#26]
HaloDBInternal.put has a hard check of the key length: https://github.com/yahoo/HaloDB/blob/master/src/main/java/com/oath/halodb/HaloDBInternal.java#L188

Is there a hard limit of 127 bytes on keys by design? Or is it intended to have longer keys using the `fixedKeySize` option? Currently it seems to be ignored altogether.

**Comment by scottcarey** [comment]
It just throws an exception and breaks if you go over 127, I don't see any reason in the code other than inefficiency (keys are written to disk twice) that the limit exists.

I suppose at that size you could substitute a ~ 16 to 24 byte hash of the key instead. If all you need is lookup, a long enough hash should be fine.    But I have run into this limit in cases where I also need to iterate over key/value pairs, and needed another indirection (map from hash to real key in another db, allowing slow scans and wasting memory).   This was too slow so I went back to another storage engine for that use case.

**Comment by wangtao724** [comment]
Mark this as duplicate to https://github.com/yahoo/HaloDB/issues/42
