### ISSUE TITLE
Enhancement: force data flush on write

### ISSUE THREAD

**Issue by ahasani** [yahoo/HaloDB#5]
Hi thanks for this awesome project. I would like to implement a volume server using HaloDB. Now as a file storage, data durability is a requirement. My question is how is it possible to enable some sort of write option to indicate that write must be written immediately to disk. Would setting options.setFlushDataSizeBytes(0) guarantee data durability?

**Comment by amannaly** [comment]
@ahasani great! glad that you find it useful.

**Comment by amannaly** [comment]
@ahasani I have added an option to enable sync writes in HaloDB for durability. 

https://github.com/yahoo/HaloDB/blob/master/src/main/java/com/oath/halodb/HaloDBOptions.java#L26
https://github.com/yahoo/HaloDB/blob/master/src/main/java/com/oath/halodb/HaloDBOptions.java#L168

But, enabling this option would significantly reduce write throughput.

**Comment by ahasani** [comment]
Wow thanks Chief. Understood about the performance impact. The significance of this is making HaloDB practically a crash only database when durability is set and guaranteed to be wriiten if put returns. Cleanup on crash is to purge last record if it was crashing during incomplete put either by size or crc. Again thanks mate really appreciate
