### ISSUE TITLE
Enhancement: Iterator seek

### ISSUE THREAD

**Issue by ahasani** [yahoo/HaloDB#6]
Dear @amannaly,

I have another use case of streaming read from and offset  (think Kafka, DistributedLog, Pulsar). I tried forwarding using `iterator.next()`. as you can guess it's  slow. Is it difficult to implement 'HaloDBIterator.seek(offset)' to start the beginning of the iterator from offset. BTW your 'forEachRemaining' is cool mate. I understand HaloDB does not order guarantee on delete or update but for this use case it will be strictly append only. 

Cheers

**Comment by amannaly** [comment]
Hi @ahasani sorry for the delayed response. 
Could you please provide some more details about your use case?
How do you define the offset here? does each record written to the database get a unique increasing offset? Or is it the offset in a file?

**Comment by ahasani** [comment]
No worries mate, really appreciate your response.
My use case is to use HaloDB as for event stream storage.
What i meant by offset is of the record. 
Your current implement HaloDBIterator is a bit slow though as it traverse the index and data file not the InMemoryIndex.
And stream storage would need timestamp in header too for TTL and expiry based compaction.
